
export const GET_PRODUCTBYID_INITIATE = 'GET_PRODUCTBYID_INITIATE'
export const GET_PRODUCTBYID_SUCCESS = 'GET_PRODUCTBYID_SUCCESS'
export const GET_PRODUCTBYID_FAILURE = 'GET_PRODUCTBYID_FAILURE'


export const GET_PRODUCTS_INITIATE = 'GET_PRODUCTS_INITIATE'
export const GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS'
export const GET_PRODUCTS_FAILURE = 'GET_PRODUCTS_FAILURE'